obj-$(CONFIG_QTI_SENSORS) += \
	cam_res_mgr/ \
	cam_sensor_utils/ \
	cam_sensor_io/ \
	cam_csiphy/ \
	cam_actuator/ \
	cam_sensor/ \
	cam_flash/ \
	cam_eeprom/ \
	cam_ir_led/ \
	cam_actuator/ \
	cam_cci/ \
	cam_csiphy/ \
	cam_eeprom/ \
	cam_flash/ \
	cam_ir_led/ \
	cam_res_mgr/ \
	cam_sensor/ \
	cam_sensor_io/ \
	cam_sensor_utils/
