# SPDX-License-Identifier: GPL-2.0-only

obj-${CONFIG_MTK_T7XX} := mtk_t7xx.o
mtk_t7xx-y:=	t7xx_pci.o \
		t7xx_isr.o \
		t7xx_pci_ats.o \
		t7xx_netdev.o \
		t7xx_buffer_manager.o \
		t7xx_dev_node.o \
		t7xx_modem_ops.o \
		t7xx_state_monitor.o  \
		t7xx_err_handler.o \
		t7xx_hif_cldma.o  \
		t7xx_ctrl_dma.o \
		t7xx_hif_dpmaif.o  \
		t7xx_dpmaif.o \
		t7xx_hif_dpmaif_rx.o  \
		t7xx_hif_dpmaif_tx.o \
		t7xx_port_config.o  \
		t7xx_port_char.o  \
		t7xx_port_ctrl_msg.o \
		t7xx_port_proxy.o  \
		t7xx_port_poll.o  \
		t7xx_port_ops.o \
		t7xx_port_wwan.o \
		t7xx_tty_ops.o
