ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_core
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_cpas/include
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_req_mgr
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_sensor_module/cam_cci
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_sensor_module/cam_res_mgr
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_sensor_module/cam_sensor_io
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_sensor_module/cam_sensor_utils
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_smmu
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_utils

obj-$(CONFIG_QTI_FLASH) += cam_flash_dev.o cam_flash_core.o cam_flash_soc.o
