# SPDX-License-Identifier: GPL-2.0-or-later
#
# Makefile for the IPTS touchscreen driver
#

obj-$(CONFIG_HID_IPTS) += ipts.o
ipts-objs := cmd.o
ipts-objs += control.o
ipts-objs += hid.o
ipts-objs += mei.o
ipts-objs += receiver.o
ipts-objs += resources.o
