#
# (C) COPYRIGHT 2012-2016 ARM Limited. All rights reserved.
#
# This program is free software and is provided to you under the terms of the
# GNU General Public License version 2 as published by the Free Software
# Foundation, and any use by you of this program is subject to the terms
# of such GNU licence.
#

ifeq ($(CONFIG_MALI_MIDGARD),y)
	obj-y += platform/rk/mali_kbase_config_rk.o
else ifeq ($(CONFIG_MALI_MIDGARD),m)
	SRC += platform/rk/mali_kbase_config_rk.c
endif
