# SPDX-License-Identifier: GPL-2.0-only

snd-soc-avs-hdaudio-objs := hdaudio.o
snd-soc-avs-dmic-objs := dmic.o
snd-soc-avs-max98357a-objs := max98357a.o
snd-soc-avs-da7219-objs := da7219.o

obj-$(CONFIG_SND_SOC_INTEL_AVS_MACH_HDAUDIO) += snd-soc-avs-hdaudio.o
obj-$(CONFIG_SND_SOC_INTEL_AVS_MACH_DMIC) += snd-soc-avs-dmic.o
obj-$(CONFIG_SND_SOC_INTEL_AVS_MACH_MAX98357A) += snd-soc-avs-max98357a.o
obj-$(CONFIG_SND_SOC_INTEL_AVS_MACH_DA7219) += snd-soc-avs-da7219.o
