ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_hyp_intf
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_utils
obj-$(CONFIG_SPECTRA_CAMERA) += cam_hyp_intf.o
