/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2019 MediaTek Inc.
 * Author: Ping-Hsun Wu <ping-hsun.wu@mediatek.com>
 */

#ifndef __MDP_REG_RSZ_H__
#define __MDP_REG_RSZ_H__

#include "mmsys_reg_base.h"

#define PRZ_ENABLE                                        (0x00000000)
#define PRZ_CONTROL_1                                     (0x00000004)
#define PRZ_CONTROL_2                                     (0x00000008)
#define PRZ_INT_FLAG                                      (0x0000000C)
#define PRZ_INPUT_IMAGE                                   (0x00000010)
#define PRZ_OUTPUT_IMAGE                                  (0x00000014)
#define PRZ_HORIZONTAL_COEFF_STEP                         (0x00000018)
#define PRZ_VERTICAL_COEFF_STEP                           (0x0000001C)
#define PRZ_LUMA_HORIZONTAL_INTEGER_OFFSET                (0x00000020)
#define PRZ_LUMA_HORIZONTAL_SUBPIXEL_OFFSET               (0x00000024)
#define PRZ_LUMA_VERTICAL_INTEGER_OFFSET                  (0x00000028)
#define PRZ_LUMA_VERTICAL_SUBPIXEL_OFFSET                 (0x0000002C)
#define PRZ_CHROMA_HORIZONTAL_INTEGER_OFFSET              (0x00000030)
#define PRZ_CHROMA_HORIZONTAL_SUBPIXEL_OFFSET             (0x00000034)
#define PRZ_RSV                                           (0x00000040)
#define PRZ_DEBUG_SEL                                     (0x00000044)
#define PRZ_DEBUG                                         (0x00000048)
#define PRZ_TAP_ADAPT                                     (0x0000004C)
#define PRZ_IBSE_SOFTCLIP                                 (0x00000050)
#define PRZ_IBSE_YLEVEL_1                                 (0x00000054)
#define PRZ_IBSE_YLEVEL_2                                 (0x00000058)
#define PRZ_IBSE_YLEVEL_3                                 (0x0000005C)
#define PRZ_IBSE_YLEVEL_4                                 (0x00000060)
#define PRZ_IBSE_YLEVEL_5                                 (0x00000064)
#define PRZ_IBSE_GAINCONTROL_1                            (0x00000068)
#define PRZ_IBSE_GAINCONTROL_2                            (0x0000006C)
#define PRZ_DEMO_IN_HMASK                                 (0x00000070)
#define PRZ_DEMO_IN_VMASK                                 (0x00000074)
#define PRZ_DEMO_OUT_HMASK                                (0x00000078)
#define PRZ_DEMO_OUT_VMASK                                (0x0000007C)
#define PRZ_SHADOW_CTRL                                   (0x000000F0)
#define PRZ_ATPG                                          (0x000000FC)
#define PRZ_PAT1_GEN_SET                                  (0x00000100)
#define PRZ_PAT1_GEN_FRM_SIZE                             (0x00000104)
#define PRZ_PAT1_GEN_COLOR0                               (0x00000108)
#define PRZ_PAT1_GEN_COLOR1                               (0x0000010C)
#define PRZ_PAT1_GEN_COLOR2                               (0x00000110)
#define PRZ_PAT1_GEN_POS                                  (0x00000114)
#define PRZ_PAT1_GEN_TILE_POS                             (0x00000124)
#define PRZ_PAT1_GEN_TILE_OV                              (0x00000128)
#define PRZ_PAT2_GEN_SET                                  (0x00000200)
#define PRZ_PAT2_GEN_COLOR0                               (0x00000208)
#define PRZ_PAT2_GEN_COLOR1                               (0x0000020C)
#define PRZ_PAT2_GEN_POS                                  (0x00000214)
#define PRZ_PAT2_GEN_CURSOR_RB0                           (0x00000218)
#define PRZ_PAT2_GEN_CURSOR_RB1                           (0x0000021C)
#define PRZ_PAT2_GEN_TILE_POS                             (0x00000224)
#define PRZ_PAT2_GEN_TILE_OV                              (0x00000228)
#define RSZ_ETC_CONTROL                                   (0x0000022C)
#define RSZ_ETC_SWITCH_MAX_MIN_1                          (0x00000230)
#define RSZ_ETC_SWITCH_MAX_MIN_2                          (0x00000234)
#define RSZ_ETC_RING_CONTROL                              (0x00000238)
#define RSZ_ETC_RING_CONTROL_GAINCONTROL_1                (0x0000023C)
#define RSZ_ETC_RING_CONTROL_GAINCONTROL_2                (0x00000240)
#define RSZ_ETC_RING_CONTROL_GAINCONTROL_3                (0x00000244)
#define RSZ_ETC_SIMILARITY_PROTECTION_GAINCONTROL_1       (0x00000248)
#define RSZ_ETC_SIMILARITY_PROTECTION_GAINCONTROL_2       (0x0000024C)
#define RSZ_ETC_SIMILARITY_PROTECTION_GAINCONTROL_3       (0x00000250)
#define RSZ_ETC_BLEND                                     (0x00000254)

// MASK
#define PRZ_ENABLE_MASK                                   (0x010001)
#define PRZ_CONTROL_1_MASK                                (0xFFFFFFF3)
#define PRZ_CONTROL_2_MASK                                (0x0FFFFAFF)
#define PRZ_INT_FLAG_MASK                                 (0x033)
#define PRZ_INPUT_IMAGE_MASK                              (0xFFFFFFFF)
#define PRZ_OUTPUT_IMAGE_MASK                             (0xFFFFFFFF)
#define PRZ_HORIZONTAL_COEFF_STEP_MASK                    (0x07FFFFF)
#define PRZ_VERTICAL_COEFF_STEP_MASK                      (0x07FFFFF)
#define PRZ_LUMA_HORIZONTAL_INTEGER_OFFSET_MASK           (0x0FFFF)
#define PRZ_LUMA_HORIZONTAL_SUBPIXEL_OFFSET_MASK          (0x01FFFFF)
#define PRZ_LUMA_VERTICAL_INTEGER_OFFSET_MASK             (0x0FFFF)
#define PRZ_LUMA_VERTICAL_SUBPIXEL_OFFSET_MASK            (0x01FFFFF)
#define PRZ_CHROMA_HORIZONTAL_INTEGER_OFFSET_MASK         (0x0FFFF)
#define PRZ_CHROMA_HORIZONTAL_SUBPIXEL_OFFSET_MASK        (0x01FFFFF)
#define PRZ_RSV_MASK                                      (0xFFFFFFFF)
#define PRZ_DEBUG_SEL_MASK                                (0x0F)
#define PRZ_DEBUG_MASK                                    (0xFFFFFFFF)
#define PRZ_TAP_ADAPT_MASK                                (0x03FFFFFF)
#define PRZ_IBSE_SOFTCLIP_MASK                            (0x0FFFFF)
#define PRZ_IBSE_YLEVEL_1_MASK                            (0xFFFFFFFF)
#define PRZ_IBSE_YLEVEL_2_MASK                            (0xFFFFFFFF)
#define PRZ_IBSE_YLEVEL_3_MASK                            (0xFFFFFFFF)
#define PRZ_IBSE_YLEVEL_4_MASK                            (0xFFFFFFFF)
#define PRZ_IBSE_YLEVEL_5_MASK                            (0x0FF3F)
#define PRZ_IBSE_GAINCONTROL_1_MASK                       (0xFFFFFFFF)
#define PRZ_IBSE_GAINCONTROL_2_MASK                       (0x0FFFFF0F)
#define PRZ_DEMO_IN_HMASK_MASK                            (0xFFFFFFFF)
#define PRZ_DEMO_IN_VMASK_MASK                            (0xFFFFFFFF)
#define PRZ_DEMO_OUT_HMASK_MASK                           (0xFFFFFFFF)
#define PRZ_DEMO_OUT_VMASK_MASK                           (0xFFFFFFFF)
#define PRZ_SHADOW_CTRL_MASK                              (0x07)
#define PRZ_ATPG_MASK                                     (0x03)
#define PRZ_PAT1_GEN_SET_MASK                             (0x0FF00FD)
#define PRZ_PAT1_GEN_FRM_SIZE_MASK                        (0x3FFF3FFF)
#define PRZ_PAT1_GEN_COLOR0_MASK                          (0x3FF03FF)
#define PRZ_PAT1_GEN_COLOR1_MASK                          (0x3FF03FF)
#define PRZ_PAT1_GEN_COLOR2_MASK                          (0x3FF03FF)
#define PRZ_PAT1_GEN_POS_MASK                             (0x3FFF3FFF)
#define PRZ_PAT1_GEN_TILE_POS_MASK                        (0x3FFF3FFF)
#define PRZ_PAT1_GEN_TILE_OV_MASK                         (0x0FFFF)
#define PRZ_PAT2_GEN_SET_MASK                             (0x0FF0003)
#define PRZ_PAT2_GEN_COLOR0_MASK                          (0x3FF03FF)
#define PRZ_PAT2_GEN_COLOR1_MASK                          (0x3FF)
#define PRZ_PAT2_GEN_POS_MASK                             (0x3FFF3FFF)
#define PRZ_PAT2_GEN_CURSOR_RB0_MASK                      (0x3FF03FF)
#define PRZ_PAT2_GEN_CURSOR_RB1_MASK                      (0x3FF)
#define PRZ_PAT2_GEN_TILE_POS_MASK                        (0x3FFF3FFF)
#define PRZ_PAT2_GEN_TILE_OV_MASK                         (0x0FFFF)
#define RSZ_ETC_CONTROL_MASK                              (0xFF770000)
#define RSZ_ETC_SWITCH_MAX_MIN_1_MASK                     (0xFFFFFFC0)
#define RSZ_ETC_SWITCH_MAX_MIN_2_MASK                     (0xFFFFFF00)
#define RSZ_ETC_RING_CONTROL_MASK                         (0xFFFFFFFF)
#define RSZ_ETC_RING_CONTROL_GAINCONTROL_1_MASK           (0xFFFFFF1F)
#define RSZ_ETC_RING_CONTROL_GAINCONTROL_2_MASK           (0xFF1FFF00)
#define RSZ_ETC_RING_CONTROL_GAINCONTROL_3_MASK           (0x1FF1FF0F)
#define RSZ_ETC_SIMILARITY_PROTECTION_GAINCONTROL_1_MASK  (0xFFFFFF3F)
#define RSZ_ETC_SIMILARITY_PROTECTION_GAINCONTROL_2_MASK  (0xFF3FFF00)
#define RSZ_ETC_SIMILARITY_PROTECTION_GAINCONTROL_3_MASK  (0x7F0FF0F)
#define RSZ_ETC_BLEND_MASK                                (0xFC000000)







#endif // __MDP_REG_RSZ_H__
