# SPDX-License-Identifier: GPL-2.0+
# Copyright (C) 2019-2020 Maximilian Luz <luzmaximilian@gmail.com>

obj-$(CONFIG_SURFACE_AGGREGATOR_CDEV)		+= surface_aggregator_cdev.o
obj-$(CONFIG_SURFACE_AGGREGATOR_REGISTRY)	+= surface_aggregator_registry.o
obj-$(CONFIG_SURFACE_ACPI_NOTIFY)		+= surface_acpi_notify.o
obj-$(CONFIG_SURFACE_BATTERY)			+= surface_battery.o
obj-$(CONFIG_SURFACE_DTX)			+= surface_dtx.o
obj-$(CONFIG_SURFACE_HID)			+= surface_hid.o
obj-$(CONFIG_SURFACE_HOTPLUG)			+= surface_hotplug.o
obj-$(CONFIG_SURFACE_PERFMODE) 			+= surface_perfmode.o
