ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_utils
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_req_mgr
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_core
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_icp
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_icp/icp_hw/include
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_icp/icp_hw/icp_hw_mgr
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_cpas/include

obj-$(CONFIG_SPECTRA_CAMERA) += icp_hw_mgr/ a5_hw/ ipe_hw/ bps_hw/
