dtb-$(CONFIG_ARCH_MEDIATEK) += mt6795-evb.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt8173-elm-rev0.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt8173-elm-rev1.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt8173-elm-rev3.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt8173-evb.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt8173-hana-rev0.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt8173-oak-rev2.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt8173-oak-rev3.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt8173-oak-rev4.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt8173-oak-rev5.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt8173-oak-rev6.dtb
dtb-$(CONFIG_ARCH_MEDIATEK) += mt8176-rowan-rev0.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
