/* SPDX-License-Identifier: GPL-2.0-only
 *
 * Copyright (c) 2021, MediaTek Inc.
 * Copyright (c) 2021, Intel Corporation.
 */

#ifndef __T7XX_REG_H__
#define __T7XX_REG_H__

/* RC part */

/* Device base address offset - update if reg BAR base is changed */
#define MHCCIF_RC_DEV_BASE    (MHCCIF_RC_DEV_BASE_CHIP)

#define REG_RC2EP_SW_BSY			0x4
#define REG_RC2EP_SW_INT_START			0x8
#define REG_RC2EP_SW_TCHNUM			0xC
#define H2D_CH_EXCEPTION_ACK			1
#define H2D_CH_EXCEPTION_CLEARQ_ACK		2
#define H2D_CH_DS_LOCK				3
/* Channels 4-8 are reserved*/
#define H2D_CH_SUSPEND_REQ			9
#define H2D_CH_RESUME_REQ			10
#define H2D_CH_SUSPEND_REQ_AP			11
#define H2D_CH_RESUME_REQ_AP			12
#define H2D_CH_DEVICE_RESET			13
#define H2D_CH_DRM_DISABLE_AP			14
#define REG_EP2RC_SW_INT_STS			0x10
#define REG_EP2RC_SW_INT_ACK			0x14
#define REG_EP2RC_SW_INT_EAP_MASK		0x20
#define REG_EP2RC_SW_INT_EAP_MASK_SET		0x30
#define REG_EP2RC_SW_INT_EAP_MASK_CLR		0x40
#define D2H_INT_DS_LOCK_ACK			BIT(0)
#define D2H_INT_EXCEPTION_INIT			BIT(1)
#define D2H_INT_EXCEPTION_INIT_DONE		BIT(2)
#define D2H_INT_EXCEPTION_CLEARQ_DONE		BIT(3)
#define D2H_INT_EXCEPTION_ALLQ_RESET		BIT(4)
#define D2H_INT_PORT_ENUM			BIT(5)
/* bits 6-10 are reserved*/
#define D2H_INT_SUSPEND_ACK			BIT(11)
#define D2H_INT_RESUME_ACK			BIT(12)
#define D2H_INT_SUSPEND_ACK_AP			BIT(13)
#define D2H_INT_RESUME_ACK_AP			BIT(14)
#define D2H_INT_ASYNC_SAP_HK			BIT(15)
#define D2H_INT_ASYNC_MD_HK			BIT(16)
#define REG_PCIE_SPARE_EP_0_REG			0x100
#define REG_PCIE_SPARE_RC_0_REG			0x120
#define MHCCIF_H2D_REG_PCIE_PM_COUNTER		0x12C

/* EP part */

/* Device base address offset - update if reg BAR base is changed */
#define MHCCIF_EP_DEV_BASE    (MHCCIF_EP_DEV_BASE_CHIP)

#define REG_EP2RC_SW_BSY			0x4
#define REG_EP2RC_SW_INT_START			0x8
#define REG_EP2RC_SW_TCHNUM			0xC
#define REG_RC2EP_SW_INT_STS			0x10
#define REG_RC2EP_SW_INT_ACK			0x14
#define REG_RC2EP_SW_INT_SAP_MASK		0x20
#define REG_RC2EP_SW_INT_USIP_MASK		0x24
#define REG_RC2EP_SW_INT_MDMCU_MASK		0x28
#define REG_RC2EP_SW_INT_SAP_MASK_SET		0x30
#define REG_RC2EP_SW_INT_USIP_MASK_SET		0x34
#define REG_RC2EP_SW_INT_MDMCU_MASK_SET		0x38
#define REG_RC2EP_SW_INT_SAP_MASK_CLR		0x40
#define REG_RC2EP_SW_INT_USIP_MASK_CLR		0x44
#define REG_RC2EP_SW_INT_MDMCU_MASK_CLR		0x48

#define REG_PCIE_DEV_SPARE_EP_0_REG		0x100
#define REG_PCIE_DEV_SPARE_EP_1_REG		0x104
#define REG_PCIE_DEV_SPARE_EP_2_REG		0x108
#define REG_PCIE_DEV_SPARE_EP_3_REG		0x10C
#define REG_PCIE_DEV_SPARE_EP_4_REG		0x110
#define REG_PCIE_DEV_SPARE_EP_5_REG		0x114
#define REG_PCIE_DEV_SPARE_EP_6_REG		0x118
#define REG_PCIE_DEV_SPARE_EP_7_REG		0x11C
#define REG_PCIE_DEV_SPARE_RC_0_REG		0x120
#define REG_PCIE_DEV_SPARE_RC_1_REG		0x124
#define REG_PCIE_DEV_SPARE_RC_2_REG		0x128
#define REG_PCIE_DEV_SPARE_RC_3_REG		0x12C
#define REG_PCIE_DEV_SPARE_RC_4_REG		0x120
#define REG_PCIE_DEV_SPARE_RC_5_REG		0x124
#define REG_PCIE_DEV_SPARE_RC_6_REG		0x128
#define REG_PCIE_DEV_SPARE_RC_7_REG		0x12C

#define MTK_DEV_T7XX			0x4D75
#define DEV_CLASS_CELLULAR_MODEM	0x0D4000

/* Reg base */
#define INFRACFG_AO_DEV_CHIP		0x10001000

/* ATR setting */
#define PCIE_REG_TRSL_ADDR_CHIP		0x10000000
#define PCIE_REG_SIZE_CHIP		0x00400000 //4MB

/* RGU */
#define TOPRGU_CH_PCIE_IRQ_STA		0x1000790C

/* AT ATR setting */
#define AT_REG_TRSL_ADDR_CHIP		0x10020000 //only cover MHCCIF range

/* IP base */
#define MHCCIF_RC_DEV_BASE_CHIP		0x10024000
#define MHCCIF_EP_DEV_BASE_CHIP		0x10025000

#define EXP_PCIE_IF_CONF		0x11460181
#define EXP_PCIE_BASIC_CONF		0x03110703

#define EXP_BAR0			0xC
#define EXP_BAR2			0x4
#define EXP_BAR4			0xC
#define EXP_BAR0_SIZE			0x8000
#define EXP_BAR2_SIZE			0x800000
#define EXP_BAR4_SIZE			0x800000

#define ATR_PORT_OFFSET			0x100
#define ATR_TABLE_OFFSET		0x20
#define ATR_TABLE_NUM_PER_ATR		8
#define ATR_TRANSPARENT_SIZE		0x3F

/* Interrupt status bits */
#define VALID_INT_START			16
#define A_ATR_INT_START			16
#define P_ATR_INT_START			20
#define EXT_INT_START			24
#define VALID_INT_END			31

#define	TOTAL_EXT_INT			8
#define	END_EXT_INT			7

/* PCIE_DEBUG_DUMMY_7 Register Description */
#define	DEV_STAGE_MASK				0x00000007
#define	HOST_EVENT_MASK				0xFFFF0000

#define	DUMMY_7_RST_TYPE_MASK			GENMASK(27, 26)
#define	DUMMY_7_RST_TYPE_PLDR			BIT(26)
#define	DUMMY_7_RST_TYPE_FLDR			BIT(27)

#define	INIT_STAGE				0
#define	LINUX_STAGE				4

/* PCIE_MAC_IREG Register Definition */

#define IREG_BASE(mtk_dev) ((mtk_dev)->base_addr.pcie_mac_ireg_base)

#define PCIE_SW_TRIG_INT			0x00BC
#define PCIE_LTSSM_STATUS			0x0150
#define ISTATUS_LOCAL				0x0184
#define INT_EN_HST				0x0188
#define ISTAT_HST				0x018C
#define PCIE_LOW_POWER_CTRL			0x0194
#define ISTAT_HST_CTRL				0x01AC
#define INT_EN_HST_SET				0x01F0
#define INT_EN_HST_CLR				0x01F4
#define PCIE_DMA_DUMMY_0			0x01F8

#define PCIE_MISC_CTRL				0x0348
#define PCIE_MISC_MAC_SLEEP_DIS			BIT(7)

#define PCIE_DUMMY_0				0x03C0
#define SW_TRIG_INTR_SET			0x03C8
#define SW_TRIG_INTR_CLR			0x03CC
#define PCIE_CFG_MSIX				0x03EC
#define ATR_PCIE_WIN0_T0_ATR_PARAM_SRC_ADDR_LSB	0x0600
#define ATR_PCIE_WIN0_T0_SRC_ADDR_MSB		0x0604
#define ATR_PCIE_WIN0_T0_TRSL_ADDR_LSB		0x0608
#define ATR_PCIE_WIN0_T0_TRSL_ADDR_MSB		0x060C
#define ATR_PCIE_WIN0_T0_TRSL_PARAM		0x0610
#define PCIE_DEBUG_DUMMY_0			0x0D00
#define PCIE_DEBUG_DUMMY_1			0x0D04
#define PCIE_DEBUG_DUMMY_2			0x0D08
#define PCIE_DEBUG_DUMMY_3			0x0D0C
#define PCIE_DEBUG_DUMMY_4			0x0D10
#define PCIE_DEBUG_DUMMY_5			0x0D14
#define PCIE_DEBUG_DUMMY_6			0x0D18
#define PCIE_DEBUG_DUMMY_7			0x0D1C
#define PCIE_RESOURCE_STATUS			0x0D28
#define DIS_ASPM_LOWPWR_SET_0			0x0E50
#define DIS_ASPM_LOWPWR_CLR_0			0x0E54
#define DIS_ASPM_LOWPWR_SET_1			0x0E58
#define DIS_ASPM_LOWPWR_CLR_1			0x0E5C
#define DIS_ASPM_LOWPWR_STS_0			0x0E60
#define DIS_ASPM_LOWPWR_STS_1			0x0E64
#define MSIX_SW_TRIG_SET_GRP0_0			0x0E80
#define MSIX_ISTAT_HST_GRP0_0			0x0F00
#define IMASK_HOST_MSIX_SET_GRP0_0		0x3000
#define IMASK_HOST_MSIX_CLR_GRP0_0		0x3080
#define IMASK_HOST_MSIX_GRP0_0			0x3100

#define L1_DISABLE_BIT(i)			BIT((i) * 4 + 1)
#define L1_1_DISABLE_BIT(i)			BIT((i) * 4 + 2)
#define L1_2_DISABLE_BIT(i)			BIT((i) * 4 + 3)

#define ATR_PCIE_WIN0_ADDR_LSB_ALGMT		0xFFFFF000

#define INT_HST_MSK				0xFFFF0000

#define	PCIE_RESOURCE_STATUS_MSK		0x1F

#define DPMAIF_PD_BASE			(0x1022D000)
#define DPMAIF_AO_BASE			(0x10014000)

#define BASE_DPMAIF_UL			(DPMAIF_PD_BASE)
#define BASE_DPMAIF_DL			(DPMAIF_PD_BASE + 0x100)
#define BASE_DPMAIF_RDMA		(DPMAIF_PD_BASE + 0x200)
#define BASE_DPMAIF_WDMA		(DPMAIF_PD_BASE + 0x300)
#define BASE_DPMAIF_AP_MISC		(DPMAIF_PD_BASE + 0x400)

#define BASE_DPMAIF_AO_UL		(DPMAIF_AO_BASE)
#define BASE_DPMAIF_AO_DL		(DPMAIF_AO_BASE + 0x400)
#define BASE_DPMAIF_PD_SRAM_MISC	(DPMAIF_PD_BASE + 0xE00)
#define BASE_DPMAIF_PD_SRAM_UL		(DPMAIF_PD_BASE + 0xD00)
#define BASE_DPMAIF_PD_SRAM_DL		(DPMAIF_PD_BASE + 0xC00)
#define BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX (DPMAIF_PD_BASE + 0x900)
#define BASE_DPMAIF_MMW_HPC		(DPMAIF_PD_BASE + 0x600)

/***********************************************************************
 * dpmaif_ul
 ***********************************************************************/
#define DPMAIF_UL_ADD_DESC		(BASE_DPMAIF_UL + 0x00)
#define DPMAIF_UL_RESTORE_RIDX		(BASE_DPMAIF_UL + 0x04)
#define DPMAIF_UL_CHNL_ARB1		(BASE_DPMAIF_UL + 0x14)
#define DPMAIF_UL_CACHE_CON0		(BASE_DPMAIF_UL + 0x70)
#define DPMAIF_UL_RDMA_CFG0		(BASE_DPMAIF_UL + 0x74)
#define DPMAIF_UL_DBG_STA0		(BASE_DPMAIF_UL + 0x80)
#define DPMAIF_UL_DBG_STA1		(BASE_DPMAIF_UL + 0x84)
#define DPMAIF_UL_DBG_STA2		(BASE_DPMAIF_UL + 0x88)
#define DPMAIF_UL_DBG_STA3		(BASE_DPMAIF_UL + 0x8C)
#define DPMAIF_UL_DBG_STA4		(BASE_DPMAIF_UL + 0x90)
#define DPMAIF_UL_DBG_STA5		(BASE_DPMAIF_UL + 0x94)
#define DPMAIF_UL_DBG_STA6		(BASE_DPMAIF_UL + 0x98)
#define DPMAIF_UL_DBG_STA7		(BASE_DPMAIF_UL + 0x9C)
#define DPMAIF_UL_DBG_STA8		(BASE_DPMAIF_UL + 0xA0)
#define DPMAIF_UL_DBG_STA9		(BASE_DPMAIF_UL + 0xA4)
#define DPMAIF_UL_RESERVE_RW		(BASE_DPMAIF_UL + 0xA8)
#define DPMAIF_UL_RESERVE_AO_RW		(BASE_DPMAIF_UL + 0xAC)
#define DPMAIF_UL_ADD_DESC_CH0		(BASE_DPMAIF_UL + 0xB0)
#define DPMAIF_UL_ADD_DESC_CH1		(BASE_DPMAIF_UL + 0xB4)
#define DPMAIF_UL_ADD_DESC_CH2		(BASE_DPMAIF_UL + 0xB8)
#define DPMAIF_UL_ADD_DESC_CH3		(BASE_DPMAIF_UL + 0xBC)
#define DPMAIF_UL_ADD_DESC_CH4		(BASE_DPMAIF_UL + 0xE0)

/***********************************************************************
 * dpmaif_dl
 ***********************************************************************/
#define DPMAIF_DL_BAT_INIT		(BASE_DPMAIF_DL + 0x00)
#define DPMAIF_DL_BAT_ADD		(BASE_DPMAIF_DL + 0x04)
#define DPMAIF_DL_BAT_INIT_CON0		(BASE_DPMAIF_DL + 0x08)
#define DPMAIF_DL_BAT_INIT_CON1		(BASE_DPMAIF_DL + 0x0C)
#define DPMAIF_DL_BAT_INIT_CON2		(BASE_DPMAIF_DL + 0x10)
#define DPMAIF_DL_PIT_INIT		(BASE_DPMAIF_DL + 0x20)
#define DPMAIF_DL_PIT_ADD		(BASE_DPMAIF_DL + 0x24)
#define DPMAIF_DL_PIT_INIT_CON0		(BASE_DPMAIF_DL + 0x28)
#define DPMAIF_DL_PIT_INIT_CON1		(BASE_DPMAIF_DL + 0x2C)
#define DPMAIF_DL_PIT_INIT_CON2		(BASE_DPMAIF_DL + 0x30)
#define DPMAIF_DL_PIT_INIT_CON5		(BASE_DPMAIF_DL + 0x14)
#define DPMAIF_DL_PIT_INIT_CON3		(BASE_DPMAIF_DL + 0x34)
#define DPMAIF_DL_CON0			(BASE_DPMAIF_DL + 0x40)
#define DPMAIF_DL_STA12			(BASE_DPMAIF_DL + 0x4C)
#define DPMAIF_DL_BAT_INIT_CON3		(BASE_DPMAIF_DL + 0x50)
#define DPMAIF_DL_PIT_INIT_CON4		(BASE_DPMAIF_DL + 0x54)
#define DPMAIF_DL_STA9			(BASE_DPMAIF_DL + 0x58)
#define DPMAIF_DL_STA10			(BASE_DPMAIF_DL + 0x5C)
#define DPMAIF_DL_STA11			(BASE_DPMAIF_DL + 0x60)
#define DPMAIF_DL_FRG_STA5		(BASE_DPMAIF_DL + 0x64)
#define DPMAIF_DL_FRG_STA6		(BASE_DPMAIF_DL + 0x68)
#define DPMAIF_DL_DBG_STA16		(BASE_DPMAIF_DL + 0x6C)
#define DPMAIF_DL_DBG_FRG0		(BASE_DPMAIF_DL + 0x70)
#define DPMAIF_DL_DBG_FRG1		(BASE_DPMAIF_DL + 0x74)
#define DPMAIF_DL_DBG_FRG2		(BASE_DPMAIF_DL + 0x78)
#define DPMAIF_DL_DBG_FRG3		(BASE_DPMAIF_DL + 0x7C)
#define DPMAIF_DL_STA0			(BASE_DPMAIF_DL + 0x80)
#define DPMAIF_DL_STA1			(BASE_DPMAIF_DL + 0x84)
#define DPMAIF_DL_STA2			(BASE_DPMAIF_DL + 0x88)
#define DPMAIF_DL_STA3			(BASE_DPMAIF_DL + 0x8C)
#define DPMAIF_DL_STA4			(BASE_DPMAIF_DL + 0x90)
#define DPMAIF_DL_STA5			(BASE_DPMAIF_DL + 0x94)
#define DPMAIF_DL_STA6			(BASE_DPMAIF_DL + 0x98)
#define DPMAIF_DL_STA7			(BASE_DPMAIF_DL + 0x9C)
#define DPMAIF_DL_STA8			(BASE_DPMAIF_DL + 0xA0)
#define DPMAIF_DL_STA13			(BASE_DPMAIF_DL + 0x18)
#define DPMAIF_DL_STA14			(BASE_DPMAIF_DL + 0x1C)
#define DPMAIF_DL_DBG_STA15		(BASE_DPMAIF_DL + 0xA4)
#define DPMAIF_DL_RESERVE_RW		(BASE_DPMAIF_DL + 0xA8)
#define DPMAIF_DL_RESERVE_AO_RW		(BASE_DPMAIF_DL + 0xAC)
#define DPMAIF_DL_DBG_STA0		(BASE_DPMAIF_DL + 0xB0)
#define DPMAIF_DL_DBG_STA1		(BASE_DPMAIF_DL + 0xB4)
#define DPMAIF_DL_DBG_STA2		(BASE_DPMAIF_DL + 0xB8)
#define DPMAIF_DL_DBG_STA3		(BASE_DPMAIF_DL + 0xBC)
#define DPMAIF_DL_DBG_STA4		(BASE_DPMAIF_DL + 0xC0)
#define DPMAIF_DL_DBG_STA5		(BASE_DPMAIF_DL + 0xC4)
#define DPMAIF_DL_DBG_STA6		(BASE_DPMAIF_DL + 0xC8)
#define DPMAIF_DL_DBG_STA7		(BASE_DPMAIF_DL + 0xCC)
#define DPMAIF_DL_DBG_STA8		(BASE_DPMAIF_DL + 0xD0)
#define DPMAIF_DL_DBG_STA9		(BASE_DPMAIF_DL + 0xD4)
#define DPMAIF_DL_DBG_STA10		(BASE_DPMAIF_DL + 0xD8)
#define DPMAIF_DL_DBG_STA11		(BASE_DPMAIF_DL + 0xDC)
#define DPMAIF_DL_FRG_STA0		(BASE_DPMAIF_DL + 0xE0)
#define DPMAIF_DL_FRG_STA1		(BASE_DPMAIF_DL + 0xE4)
#define DPMAIF_DL_FRG_STA2		(BASE_DPMAIF_DL + 0xE8)
#define DPMAIF_DL_FRG_STA3		(BASE_DPMAIF_DL + 0xEC)
#define DPMAIF_DL_FRG_STA4		(BASE_DPMAIF_DL + 0xF0)
#define DPMAIF_DL_DBG_STA12		(BASE_DPMAIF_DL + 0xF4)
#define DPMAIF_DL_DBG_STA13		(BASE_DPMAIF_DL + 0xF8)
#define DPMAIF_DL_DBG_STA14		(BASE_DPMAIF_DL + 0xFC)

/***********************************************************************
 * dpmaif_ap_misc
 ***********************************************************************/
#define DPMAIF_AP_L2TISAR0		(BASE_DPMAIF_AP_MISC + 0x00)
#define DPMAIF_AP_L1TISAR0		(BASE_DPMAIF_AP_MISC + 0x10)
#define DPMAIF_AP_L1TIMR0		(BASE_DPMAIF_AP_MISC + 0x14)
#define DPMAIF_AP_BUS_CONFIG0		(BASE_DPMAIF_AP_MISC + 0x20)
#define DPMAIF_AP_TOP_AP_CFG		(BASE_DPMAIF_AP_MISC + 0x24)
#define DPMAIF_AP_EMI_BUS_STATUS0	(BASE_DPMAIF_AP_MISC + 0x30)
#define DPMAIF_AP_PCIE_BUS_STATUS0	(BASE_DPMAIF_AP_MISC + 0x34)
#define DPMAIF_AP_DMA_ERR_STA		(BASE_DPMAIF_AP_MISC + 0x40)
#define DPMAIF_AP_APDL_L2TISAR0		(BASE_DPMAIF_AP_MISC + 0x50)
#define DPMAIF_AP_IP_BUSY		(BASE_DPMAIF_AP_MISC + 0x60)
#define DPMAIF_AP_CG_EN			(BASE_DPMAIF_AP_MISC + 0x68)
#define DPMAIF_AP_CODA_VER		(BASE_DPMAIF_AP_MISC + 0x6C)
#define DPMAIF_AP_APB_DBG_SRAM		(BASE_DPMAIF_AP_MISC + 0x70)

#define DPMAIF_AP_HPC_SRAM_USAGE	(BASE_DPMAIF_AP_MISC + 0x74)
#define DPMAIF_AP_MPIT_CACHE_INV	(BASE_DPMAIF_AP_MISC + 0x80)
#define DPMAIF_AP_OVERWRITE_CFG		(BASE_DPMAIF_AP_MISC + 0x90)

#define DPMAIF_AP_MEM_CLR		(BASE_DPMAIF_AP_MISC + 0x94)

/***********************************************************************
 * dpmaif_ao_ul
 **********************************************************************/
#define DPMAIF_AO_UL_INIT_SET		(BASE_DPMAIF_AO_UL + 0x0)

#define DPMAIF_AO_UL_CHNL_ARB0		(BASE_DPMAIF_AO_UL + 0x1C)
#define DPMAIF_AO_UL_AP_L2TIMR0		(BASE_DPMAIF_AO_UL + 0x80)
#define DPMAIF_AO_UL_AP_L2TIMCR0	(BASE_DPMAIF_AO_UL + 0x84)
#define DPMAIF_AO_UL_AP_L2TIMSR0	(BASE_DPMAIF_AO_UL + 0x88)
#define DPMAIF_AO_UL_AP_L1TIMR0		(BASE_DPMAIF_AO_UL + 0x8C)
#define DPMAIF_AO_UL_APDL_L2TIMR0	(BASE_DPMAIF_AO_UL + 0x90)
#define DPMAIF_AO_UL_APDL_L2TIMCR0	(BASE_DPMAIF_AO_UL + 0x94)
#define DPMAIF_AO_UL_APDL_L2TIMSR0	(BASE_DPMAIF_AO_UL + 0x98)
#define DPMAIF_AO_AP_DLUL_IP_BUSY_MASK	(BASE_DPMAIF_AO_UL + 0x9C)

/***********************************************************************
 * dpmaif_pd_sram_ul
 **********************************************************************/
#define DPMAIF_AO_UL_MD_RDY_CNT_TH	(BASE_DPMAIF_PD_SRAM_UL + 0x0)
#define DPMAIF_AO_ULQN_MAX_PKT_SZ	(BASE_DPMAIF_PD_SRAM_UL + 0x4)
#define DPMAIF_AO_UL_CH_WEIGHT0		(BASE_DPMAIF_PD_SRAM_UL + 0x8)
#define DPMAIF_AO_UL_CH_WEIGHT1		(BASE_DPMAIF_PD_SRAM_UL + 0xC)
#define DPMAIF_AO_UL_CHNL0_CON0		(BASE_DPMAIF_PD_SRAM_UL + 0x10)
#define DPMAIF_AO_UL_CHNL0_CON1		(BASE_DPMAIF_PD_SRAM_UL + 0x14)
#define DPMAIF_AO_UL_CHNL0_CON2		(BASE_DPMAIF_PD_SRAM_UL + 0x18)
#define DPMAIF_AO_UL_CHNL1_CON0		(BASE_DPMAIF_PD_SRAM_UL + 0x20)
#define DPMAIF_AO_UL_CHNL1_CON1		(BASE_DPMAIF_PD_SRAM_UL + 0x24)
#define DPMAIF_AO_UL_CHNL1_CON2		(BASE_DPMAIF_PD_SRAM_UL + 0x28)
#define DPMAIF_AO_UL_CHNL2_CON0		(BASE_DPMAIF_PD_SRAM_UL + 0x30)
#define DPMAIF_AO_UL_CHNL2_CON1		(BASE_DPMAIF_PD_SRAM_UL + 0x34)
#define DPMAIF_AO_UL_CHNL2_CON2		(BASE_DPMAIF_PD_SRAM_UL + 0x38)
#define DPMAIF_AO_UL_CHNL3_CON0		(BASE_DPMAIF_PD_SRAM_UL + 0x40)
#define DPMAIF_AO_UL_CHNL3_CON1		(BASE_DPMAIF_PD_SRAM_UL + 0x44)
#define DPMAIF_AO_UL_CHNL3_CON2		(BASE_DPMAIF_PD_SRAM_UL + 0x48)
#define DPMAIF_AO_UL_CHNL4_CON0		(BASE_DPMAIF_PD_SRAM_UL + 0x50)
#define DPMAIF_AO_UL_CHNL4_CON1		(BASE_DPMAIF_PD_SRAM_UL + 0x54)
#define DPMAIF_AO_UL_CHNL4_CON2		(BASE_DPMAIF_PD_SRAM_UL + 0x58)
#define DPMAIF_AO_UL_CH0_STA		(BASE_DPMAIF_PD_SRAM_UL + 0x70)
#define DPMAIF_AO_UL_CH1_STA		(BASE_DPMAIF_PD_SRAM_UL + 0x74)
#define DPMAIF_AO_UL_CH2_STA		(BASE_DPMAIF_PD_SRAM_UL + 0x78)
#define DPMAIF_AO_UL_CH3_STA		(BASE_DPMAIF_PD_SRAM_UL + 0x7C)
#define DPMAIF_AO_UL_CH4_STA		(BASE_DPMAIF_PD_SRAM_UL + 0x80)
#define DPMAIF_AO_UL_CH_WIDX01		(BASE_DPMAIF_PD_SRAM_UL + 0x84)
#define DPMAIF_AO_UL_CH_WIDX23		(BASE_DPMAIF_PD_SRAM_UL + 0x88)
#define DPMAIF_AO_UL_CH_WIDX4		(BASE_DPMAIF_PD_SRAM_UL + 0x8C)

/***********************************************************************
 *	dpmaif_ao_dl
 **********************************************************************/
#define DPMAIF_AO_DL_INIT_SET		(BASE_DPMAIF_AO_DL + 0x0)
#define DPMAIF_AO_DL_INIT_RESTORE_CFG	(BASE_DPMAIF_AO_DL + 0x4)
#define DPMAIF_AO_DL_IRQ_MASK		(BASE_DPMAIF_AO_DL + 0xC)
#define DPMAIF_AO_DL_DLQPIT_INIT_CON5	(BASE_DPMAIF_AO_DL + 0x28)
#define DPMAIF_AO_DL_DLQPIT_TRIG_THRES	(BASE_DPMAIF_AO_DL + 0x34)

#define DPMAIF_AO_DL_AO_ABI_EN		(BASE_DPMAIF_AO_DL + 0x60)
#define DPMAIF_AO_DL_AO_SBI_EN		(BASE_DPMAIF_AO_DL + 0x64)
#define DPMAIF_AO_DL_AO_PA_OFS_L	(BASE_DPMAIF_AO_DL + 0x68)
#define DPMAIF_AO_DL_AO_PA_OFS_H	(BASE_DPMAIF_AO_DL + 0x6C)
#define DPMAIF_AO_DL_AO_SCP_DL_MASK	(BASE_DPMAIF_AO_DL + 0x70)
#define DPMAIF_AO_DL_AO_SCP_UL_MASK	(BASE_DPMAIF_AO_DL + 0x74)

/***********************************************************************
 *	dpmaif_pd_sram_dl
 **********************************************************************/
#define DPMAIF_AO_DL_PKTINFO_CON0	(BASE_DPMAIF_PD_SRAM_DL + 0x0)
#define DPMAIF_AO_DL_PKTINFO_CON1	(BASE_DPMAIF_PD_SRAM_DL + 0x4)
#define DPMAIF_AO_DL_PKTINFO_CON2	(BASE_DPMAIF_PD_SRAM_DL + 0x8)
#define DPMAIF_AO_DL_RDY_CHK_THRES	(BASE_DPMAIF_PD_SRAM_DL + 0xC)
#define DPMAIF_AO_DL_RDY_CHK_FRG_THRES	(BASE_DPMAIF_PD_SRAM_DL + 0x10)
#define DPMAIF_AO_DL_REORDER_BITMAP_CACHE	(BASE_DPMAIF_PD_SRAM_DL + 0x14)
#define DPMAIF_AO_DL_REORDER_CACHE	(BASE_DPMAIF_PD_SRAM_DL + 0x18)
#define DPMAIF_AO_DL_REORDER_THRES	(BASE_DPMAIF_PD_SRAM_DL + 0x1C)

#define DPMAIF_AO_DL_DLQ_AGG_CFG	(BASE_DPMAIF_PD_SRAM_DL + 0x20)
#define DPMAIF_AO_DL_DLQPIT_TIMEOUT0	(BASE_DPMAIF_PD_SRAM_DL + 0x24)
#define DPMAIF_AO_DL_DLQPIT_TIMEOUT1	(BASE_DPMAIF_PD_SRAM_DL + 0x28)
#define DPMAIF_AO_DL_DLQPIT_TIMEOUT2	(BASE_DPMAIF_PD_SRAM_DL + 0x2C)
#define DPMAIF_AO_DL_DLQPIT_TIMEOUT3	(BASE_DPMAIF_PD_SRAM_DL + 0x30)
#define DPMAIF_AO_DL_DLQPIT_TIMEOUT4	(BASE_DPMAIF_PD_SRAM_DL + 0x34)
#define DPMAIF_AO_DL_HPC_CNTL		(BASE_DPMAIF_PD_SRAM_DL + 0x38)
#define DPMAIF_AO_DL_PIT_SEQ_END	(BASE_DPMAIF_PD_SRAM_DL + 0x40)

#define DPMAIF_AO_DL_BAT_STA0		(BASE_DPMAIF_PD_SRAM_DL + 0xD0)
#define DPMAIF_AO_DL_BAT_STA1		(BASE_DPMAIF_PD_SRAM_DL + 0xD4)
#define DPMAIF_AO_DL_BAT_STA2		(BASE_DPMAIF_PD_SRAM_DL + 0xD8)
#define DPMAIF_AO_DL_BAT_STA3		(BASE_DPMAIF_PD_SRAM_DL + 0xDC)
#define DPMAIF_AO_DL_BAT_STA4		(BASE_DPMAIF_PD_SRAM_DL + 0xE0)
#define DPMAIF_AO_DL_PIT_STA0		(BASE_DPMAIF_PD_SRAM_DL + 0xE4)
#define DPMAIF_AO_DL_PIT_STA1		(BASE_DPMAIF_PD_SRAM_DL + 0xE8)
#define DPMAIF_AO_DL_PIT_STA2		(BASE_DPMAIF_PD_SRAM_DL + 0xEC)
#define DPMAIF_AO_DL_PIT_STA3		(BASE_DPMAIF_PD_SRAM_DL + 0x60)
#define DPMAIF_AO_DL_PIT_STA4		(BASE_DPMAIF_PD_SRAM_DL + 0x64)
#define DPMAIF_AO_DL_PIT_STA5		(BASE_DPMAIF_PD_SRAM_DL + 0x68)
#define DPMAIF_AO_DL_PIT_STA6		(BASE_DPMAIF_PD_SRAM_DL + 0x6C)
#define DPMAIF_AO_DL_FRGBAT_STA0	(BASE_DPMAIF_PD_SRAM_DL + 0x70)
#define DPMAIF_AO_DL_FRGBAT_STA1	(BASE_DPMAIF_PD_SRAM_DL + 0x74)
#define DPMAIF_AO_DL_FRGBAT_STA2	(BASE_DPMAIF_PD_SRAM_DL + 0x78)
#define DPMAIF_AO_DL_FRGBAT_STA3	(BASE_DPMAIF_PD_SRAM_DL + 0x7C)
#define DPMAIF_AO_DL_FRGBAT_STA4	(BASE_DPMAIF_PD_SRAM_DL + 0x80)

#define DPMAIF_AO_DL_DLQ_STA0		(BASE_DPMAIF_PD_SRAM_DL + 0x90)
#define DPMAIF_AO_DL_DLQ_STA1		(BASE_DPMAIF_PD_SRAM_DL + 0x94)
#define DPMAIF_AO_DL_DLQ_STA2		(BASE_DPMAIF_PD_SRAM_DL + 0x98)
#define DPMAIF_AO_DL_DLQ_STA3		(BASE_DPMAIF_PD_SRAM_DL + 0x9C)
#define DPMAIF_AO_DL_DLQ_STA4		(BASE_DPMAIF_PD_SRAM_DL + 0xA0)
#define DPMAIF_AO_DL_DLQ_STA5		(BASE_DPMAIF_PD_SRAM_DL + 0xA4)
#define DPMAIF_AO_DL_DLQ_STA6		(BASE_DPMAIF_PD_SRAM_DL + 0xA8)
#define DPMAIF_AO_DL_DLQ_STA8		(BASE_DPMAIF_PD_SRAM_DL + 0xB0)
#define DPMAIF_AO_DL_DLQ_STA9		(BASE_DPMAIF_PD_SRAM_DL + 0xB4)
#define DPMAIF_AO_DL_DLQ_STA10		(BASE_DPMAIF_PD_SRAM_DL + 0xB8)
#define DPMAIF_AO_DL_DLQ_STA11		(BASE_DPMAIF_PD_SRAM_DL + 0xBC)
#define DPMAIF_AO_DL_DLQ_STA12		(BASE_DPMAIF_PD_SRAM_DL + 0xC0)
#define DPMAIF_AO_DL_DLQ_STA13		(BASE_DPMAIF_PD_SRAM_DL + 0xC4)
#define DPMAIF_AO_DL_DLQ_STA14		(BASE_DPMAIF_PD_SRAM_DL + 0xC8)

/***********************************************************************
 *	dpmaif_hpc
 **********************************************************************/
#define DPMAIF_HPC_ENTRY_STS0		(BASE_DPMAIF_MMW_HPC + 0x004)
#define DPMAIF_HPC_ENTRY_STS1		(BASE_DPMAIF_MMW_HPC + 0x008)
#define DPMAIF_HPC_ENTRY_CICO_STS	(BASE_DPMAIF_MMW_HPC + 0x00C)
#define DPMAIF_HPC_CI_CO0		(BASE_DPMAIF_MMW_HPC + 0x010)
#define DPMAIF_HPC_CI_CO1		(BASE_DPMAIF_MMW_HPC + 0x014)
#define DPMAIF_HPC_CI_CO2		(BASE_DPMAIF_MMW_HPC + 0x018)
#define DPMAIF_HPC_CI_CO3		(BASE_DPMAIF_MMW_HPC + 0x01C)
#define DPMAIF_HPC_CI_CO4		(BASE_DPMAIF_MMW_HPC + 0x020)
#define DPMAIF_HPC_CI_CO5		(BASE_DPMAIF_MMW_HPC + 0x024)
#define DPMAIF_HPC_CI_CO6		(BASE_DPMAIF_MMW_HPC + 0x028)
#define DPMAIF_HPC_CI_CO7		(BASE_DPMAIF_MMW_HPC + 0x02C)
#define DPMAIF_HPC_SW_5TUPLE_TRIG	(BASE_DPMAIF_MMW_HPC + 0x030)
#define DPMAIF_HPC_5TUPLE_STS		(BASE_DPMAIF_MMW_HPC + 0x034)
#define DPMAIF_HPC_RULE_TGL		(BASE_DPMAIF_MMW_HPC + 0x038)
#define DPMAIF_HPC_HASH_0TO3		(BASE_DPMAIF_MMW_HPC + 0x040)
#define DPMAIF_HPC_HASH_4TO7		(BASE_DPMAIF_MMW_HPC + 0x044)
#define DPMAIF_HPC_TYPE			(BASE_DPMAIF_MMW_HPC + 0x048)
#define DPMAIF_PARSE_TCP_DATA_OFS	(BASE_DPMAIF_MMW_HPC + 0x04C)
#define DPMAIF_HPC_OPT_IDX01		(BASE_DPMAIF_MMW_HPC + 0x050)
#define DPMAIF_HPC_OPT_IDX23		(BASE_DPMAIF_MMW_HPC + 0x054)
#define DPMAIF_HPC_OPT_IDX45		(BASE_DPMAIF_MMW_HPC + 0x058)
#define DPMAIF_HPC_OPT_IDX67		(BASE_DPMAIF_MMW_HPC + 0x05C)
#define DPMAIF_HPC_SW_ADD_RULE0		(BASE_DPMAIF_MMW_HPC + 0x060)
#define DPMAIF_HPC_SW_ADD_RULE1		(BASE_DPMAIF_MMW_HPC + 0x064)
#define DPMAIF_HPC_SW_ADD_RULE2		(BASE_DPMAIF_MMW_HPC + 0x068)
#define DPMAIF_HPC_SW_ADD_RULE3		(BASE_DPMAIF_MMW_HPC + 0x06C)
#define DPMAIF_HPC_SW_ADD_RULE4		(BASE_DPMAIF_MMW_HPC + 0x070)
#define DPMAIF_HPC_SW_ADD_RULE5		(BASE_DPMAIF_MMW_HPC + 0x074)
#define DPMAIF_HPC_SW_ADD_RULE6		(BASE_DPMAIF_MMW_HPC + 0x078)
#define DPMAIF_HPC_SW_ADD_RULE7		(BASE_DPMAIF_MMW_HPC + 0x07C)
#define DPMAIF_HPC_SW_ADD_RULE8		(BASE_DPMAIF_MMW_HPC + 0x080)
#define DPMAIF_HPC_SW_ADD_RULE9		(BASE_DPMAIF_MMW_HPC + 0x084)
#define DPMAIF_HPC_CICO_THLD		(BASE_DPMAIF_MMW_HPC + 0x090)
#define DPMAIF_HPC_CICO_COUNT		(BASE_DPMAIF_MMW_HPC + 0x094)
#define DPMAIF_HPC_CICO_STS		(BASE_DPMAIF_MMW_HPC + 0x098)
#define DPMAIF_HPC_INTR_STS_W1C		(BASE_DPMAIF_MMW_HPC + 0x0F0)
#define DPMAIF_HPC_INTR_MASK		(BASE_DPMAIF_MMW_HPC + 0x0F4)
#define DPMAIF_HPC_BKDR			(BASE_DPMAIF_MMW_HPC + 0x100)
#define DPMAIF_HPC_BKDR_EN0		(BASE_DPMAIF_MMW_HPC + 0x104)
#define DPMAIF_HPC_BKDR_EN1		(BASE_DPMAIF_MMW_HPC + 0x108)
#define DPMAIF_HPC_BKDR_EN2		(BASE_DPMAIF_MMW_HPC + 0x10C)
#define DPMAIF_HPC_ENTRY_STS0_BKDR	(BASE_DPMAIF_MMW_HPC + 0x110)
#define DPMAIF_HPC_TYPE_BKDR		(BASE_DPMAIF_MMW_HPC + 0x114)
#define DPMAIF_PARSE_TCP_DATA_OFS_BKDR	(BASE_DPMAIF_MMW_HPC + 0x118)
#define DPMAIF_HPC_OPT_IDX01_BKDR	(BASE_DPMAIF_MMW_HPC + 0x120)
#define DPMAIF_HPC_OPT_IDX23_BKDR	(BASE_DPMAIF_MMW_HPC + 0x124)
#define DPMAIF_HPC_OPT_IDX45_BKDR	(BASE_DPMAIF_MMW_HPC + 0x128)
#define DPMAIF_HPC_OPT_IDX67_BKDR	(BASE_DPMAIF_MMW_HPC + 0x12C)
#define DPMAIF_HPC_CI_CO_0_BKDR		(BASE_DPMAIF_MMW_HPC + 0x130)
#define DPMAIF_HPC_CI_CO_1_BKDR		(BASE_DPMAIF_MMW_HPC + 0x134)
#define DPMAIF_HPC_CI_CO_2_BKDR		(BASE_DPMAIF_MMW_HPC + 0x138)
#define DPMAIF_HPC_CI_CO_3_BKDR		(BASE_DPMAIF_MMW_HPC + 0x13C)
#define DPMAIF_HPC_CI_CO_4_BKDR		(BASE_DPMAIF_MMW_HPC + 0x140)
#define DPMAIF_HPC_CI_CO_5_BKDR		(BASE_DPMAIF_MMW_HPC + 0x144)
#define DPMAIF_HPC_CI_CO_6_BKDR		(BASE_DPMAIF_MMW_HPC + 0x148)
#define DPMAIF_HPC_CI_CO_7_BKDR		(BASE_DPMAIF_MMW_HPC + 0x14C)
#define DPMAIF_HPC_HASH_0TO3_BKDR	(BASE_DPMAIF_MMW_HPC + 0x150)
#define DPMAIF_HPC_HASH_4TO7_BKDR	(BASE_DPMAIF_MMW_HPC + 0x154)
#define DPMAIF_HPC_CICO_COUNT_BKDR	(BASE_DPMAIF_MMW_HPC + 0x158)
#define DPMAIF_HPC_RULE_TGL_BKDR	(BASE_DPMAIF_MMW_HPC + 0x15C)
#define DPMAIF_HPC_STAT0		(BASE_DPMAIF_MMW_HPC + 0x1A0)
#define DPMAIF_HPC_STAT1		(BASE_DPMAIF_MMW_HPC + 0x1A4)
#define DPMAIF_HPC_DUMMY0		(BASE_DPMAIF_MMW_HPC + 0x1E0)
#define DPMAIF_HPC_DUMMY1		(BASE_DPMAIF_MMW_HPC + 0x1E4)
#define DPMAIF_HPC_DEBUG_MON_0		(BASE_DPMAIF_MMW_HPC + 0x1E8)
#define DPMAIF_HPC_DEBUG_MON_1		(BASE_DPMAIF_MMW_HPC + 0x1EC)
#define DPMAIF_HPC_DEBUG_MON_2		(BASE_DPMAIF_MMW_HPC + 0x1F0)
#define DPMAIF_HPC_DEBUG_MON_3		(BASE_DPMAIF_MMW_HPC + 0x1F4)
#define DPMAIF_HPC_DEBUG_MON_4		(BASE_DPMAIF_MMW_HPC + 0x1F8)
#define DPMAIF_HPC_VER			(BASE_DPMAIF_MMW_HPC + 0x1FC)

/***********************************************************************
 *	dpmaif_dlq
 **********************************************************************/
#define DPMAIF_DL_DLQPIT_INIT		(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0x0)
#define DPMAIF_DL_DLQPIT_ADD		(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0x10)
#define DPMAIF_DL_DLQPIT_INIT_CON0	(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0x14)
#define DPMAIF_DL_DLQPIT_INIT_CON1	(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0x18)
#define DPMAIF_DL_DLQPIT_INIT_CON2	(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0x1C)
#define DPMAIF_DL_DLQPIT_INIT_CON3	(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0x20)
#define DPMAIF_DL_DLQPIT_INIT_CON4	(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0x24)
#define DPMAIF_DL_DLQPIT_INIT_CON5	(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0x28)
#define DPMAIF_DL_DLQPIT_INIT_CON6	(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0x2C)
#define DPMAIF_DL_DLQPIT_SW_TRIG	(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0x30)
#define DPMAIF_DL_DLQ_TIMER_GATED	(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0x34)
#define DPMAIF_DL_DLQ_CUR_HF_0		(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0x38)
#define DPMAIF_DL_DLQ_DBG_CFG0		(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0x40)
#define DPMAIF_DL_DLQ_DBG_STA0		(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0x44)
#define DPMAIF_DL_DLQ_DBG_STA1		(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0x48)
#define DPMAIF_DL_DLQ_DBG_STA2		(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0x4C)
#define DPMAIF_DL_DLQ_CUR_HF_1		(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0x50)
#define DPMAIF_DL_DLQ_CUR_HF_2		(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0x54)
#define DPMAIF_DL_DLQ_CUR_HF_3		(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0x58)
#define DPMAIF_DL_DLQ_CUR_HF_4		(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0x5C)
#define DPMAIF_DL_DLQ_DBG_SEL		(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0x64)
#define DPMAIF_DL_DLQ_CACHE_DBG_SEL	(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0x68)
#define DPMAIF_DL_DLQ_DBG_OUT0		(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0x6C)
#define DPMAIF_DL_DLQ_CACHE_DBG_OUT0	(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0x70)
#define DPMAIF_DL_DLQ_CACHE_DBG_OUT1	(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0x74)
#define DPMAIF_DL_DLQ_CACHE_DBG_OUT2	(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0x78)
#define DPMAIF_DL_DLQ_CACHE_DBG_OUT3	(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0x7C)
#define DPMAIF_DL_DLQ_STA0		(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0x80)
#define DPMAIF_DL_DLQ_STA1		(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0x84)
#define DPMAIF_DL_DLQ_STA2		(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0x88)
#define DPMAIF_DL_DLQ_STA3		(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0x8C)
#define DPMAIF_DL_DLQ_STA4		(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0x90)
#define DPMAIF_DL_DLQ_STA5		(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0x94)
#define DPMAIF_DL_DLQ_STA6		(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0x98)
#define DPMAIF_DL_DLQ_STA7		(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0x9C)
#define DPMAIF_DL_DLQ_STA8		(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0xA0)
#define DPMAIF_DL_DLQ_STA9		(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0xA4)
#define DPMAIF_DL_DLQ_STAA		(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0xC0)
#define DPMAIF_DL_DLQ_STAB		(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0xC4)
#define DPMAIF_DL_DLQ_STAC		(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0xC8)
#define DPMAIF_DL_DLQ_STAD		(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0xCC)
#define DPMAIF_DL_AGG_STA		(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0xA8)
#define DPMAIF_DL_DLQPIT_TIMER0		(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0xAC)
#define DPMAIF_DL_DLQPIT_TIMER1		(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0xB0)
#define DPMAIF_DL_DLQPIT_TIMER2		(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0xB4)
#define DPMAIF_DL_DLQPIT_TIMER3		(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0xB8)
#define DPMAIF_DL_DLQPIT_TIMER4		(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0xBC)
#define DPMAIF_DL_AGG_WIDX1		(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0xD0)
#define DPMAIF_DL_AGG_WIDX2		(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0xD4)
#define DPMAIF_DL_AGG_WIDX3		(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0xD8)
#define DPMAIF_DL_AGG_WIDX4		(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0xDC)
#define DPMAIF_DL_AGG_STA_IDX		(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0xE0)
#define DPMAIF_DL_DLQ_CACHE_DBG_OUT4	(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0xF0)
#define DPMAIF_DL_DLQ_CACHE_DBG_OUT5	(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0xF4)
#define DPMAIF_DL_DLQ_CACHE_DBG_OUT6	(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0xF8)
#define DPMAIF_DL_DLQ_CACHE_DBG_OUT7	(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0xFC)
#define DPMAIF_DL_DLQ_DBG_MODULE1	(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0xE4)
#define DPMAIF_DL_DLQ_DBG_MODULE2	(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0xE8)
#define DPMAIF_DL_DLQ_DBG_MODULE3	(BASE_DPMAIF_DL_DLQ_REMOVEAO_IDX + 0xEC)

/***********************************************************************
 *	common include function
 **********************************************************************/
#define DPMAIF_ULQSAR_n(q)		(DPMAIF_AO_UL_CHNL0_CON0 + 0x10 * (q))
#define DPMAIF_UL_DRBSIZE_ADDRH_n(q)	(DPMAIF_AO_UL_CHNL0_CON1 + 0x10 * (q))
#define DPMAIF_UL_DRB_ADDRH_n(q)	(DPMAIF_AO_UL_CHNL0_CON2 + 0x10 * (q))
#define DPMAIF_ULQ_STA0_n(q)		(DPMAIF_AO_UL_CH0_STA + 0x04 * (q))
#define DPMAIF_ULQ_ADD_DESC_CH_n(q)	(DPMAIF_UL_ADD_DESC_CH0 + 0x04 * (q))

#define DPMAIF_UL_DRB_RIDX_OFFSET		16

#define DPMAIF_AP_RGU_ASSERT			0x10001150
#define DPMAIF_AP_RGU_DEASSERT			0x10001154
#define DPMAIF_AP_RST_BIT			BIT(2)

#define DPMAIF_AP_AO_RGU_ASSERT			0x10001140
#define DPMAIF_AP_AO_RGU_DEASSERT		0x10001144
#define DPMAIF_AP_AO_RST_BIT			BIT(6)

/***********************************************************************
 *	DPMAIF init/restore
 **********************************************************************/
#define DPMAIF_UL_ADD_NOT_READY			BIT(31)
#define DPMAIF_UL_RESTORE_NOT_READY		BIT(31)
#define DPMAIF_UL_ADD_UPDATE			BIT(31)
#define DPMAIF_UL_ALL_QUE_ARB_EN		(0xF << 8)

#define DPMAIF_DL_ADD_UPDATE			BIT(31)
#define DPMAIF_DL_ADD_NOT_READY			BIT(31)
#define DPMAIF_DL_FRG_ADD_UPDATE		BIT(16)

#define DPMAIF_DL_BAT_INIT_ALLSET		BIT(0)
#define DPMAIF_DL_BAT_FRG_INIT			BIT(16)
#define DPMAIF_DL_BAT_INIT_EN			BIT(31)
#define DPMAIF_DL_BAT_INIT_NOT_READY		BIT(31)
#define DPMAIF_DL_BAT_INIT_ONLY_ENABLE_BIT	(0 << 0)

#define DPMAIF_DL_PIT_INIT_ALLSET		BIT(0)
#define DPMAIF_DL_PIT_INIT_EN			BIT(31)
#define DPMAIF_DL_PIT_INIT_NOT_READY		BIT(31)

#define DPMAIF_PKT_ALIGN64_MODE			0
#define DPMAIF_PKT_ALIGN128_MODE		1

#define DPMAIF_BAT_REMAIN_SZ_BASE		16
#define DPMAIF_BAT_BUFFER_SZ_BASE		128
#define DPMAIF_FRG_BUFFER_SZ_BASE		128

#define DPMAIF_PIT_EN_MSK			0x01
#define DLQ_PIT_IDX_SIZE			0x20

#define DPMAIF_PIT_SIZE_MSK			0x3FFFF

#define DPMAIF_PIT_REM_CNT_MSK			0x0003FFFF
#define DPMAIF_PIT_ADDRH_MSK			0xF0000000

#define DPMAIF_BAT_EN_MSK			BIT(16)
#define DPMAIF_FRG_EN_MSK			BIT(28)
#define DPMAIF_BAT_SIZE_MSK			0xFFFF
#define DPMAIF_BAT_ADDRH_MSK			0xF0000000

#define DPMAIF_BAT_BID_MAXCNT_MSK		0xFFFF0000
#define DPMAIF_BAT_REMAIN_MINSZ_MSK		0x0000FF00
#define DPMAIF_PIT_CHK_NUM_MSK			0xFF000000
#define DPMAIF_BAT_BUF_SZ_MSK			0x0001FF00
#define DPMAIF_FRG_BUF_SZ_MSK			0x0001FF00
#define DPMAIF_BAT_RSV_LEN_MSK			0x000000FF
#define DPMAIF_PKT_ALIGN_MSK			(0x3 << 22)

#define DPMAIF_BAT_CHECK_THRES_MSK		(0x3F << 16)
#define DPMAIF_FRG_CHECK_THRES_MSK		(0xFF)
#define DPMAIF_AO_DL_ISR_MSK			(0x3F)

#define DPMAIF_PKT_ALIGN_EN			BIT(23)

#define DPMAIF_DRB_ADDRH_MSK			0xFF000000
#define DPMAIF_DRB_SIZE_MSK			0x0000FFFF

#define DPMAIF_DL_PIT_WRIDX_MSK			0x3FFFF
#define DPMAIF_DL_BAT_WRIDX_MSK			0x3FFFF
#define DPMAIF_DL_FRG_WRIDX_MSK			0x3FFFF

/* DPMAIF_PD_UL_DBG_STA2 */
#define DPMAIF_UL_IDLE_STS			BIT(11)
/* DPMAIF_PD_DL_DBG_STA1 */
#define DPMAIF_DL_IDLE_STS			BIT(23)
/* DPMAIF_AO_DL_RDY_CHK_THRES */
#define DPMAIF_DL_PKT_CHECKSUM_EN		BIT(31)
#define DPMAIF_PORT_MODE_PCIE			BIT(30)
#define DPMAIF_DL_BURST_PIT_EN			BIT(13)
/* BAT CACHE PRI */
#define DPMAIF_DL_BAT_CACHE_PRI			BIT(22)
/* DPMAIF_AP_MEM_CLR */
#define DPMAIF_MEM_CLR				BIT(0)
/* DPMAIF_AP_OVERWRITE_CFG */
#define DPMAIF_SRAM_SYNC			BIT(0)
/* DPMAIF_AO_UL_INIT_SET */
#define DPMAIF_UL_INIT_DONE			BIT(0)
/* DPMAIF_AO_DL_INIT_SET */
#define DPMAIF_DL_INIT_DONE			BIT(0)
/* DPMAIF_AO_DL_PIT_SEQ_END */
#define DPMAIF_DL_PIT_SEQ_MSK			(0xFF)
/* DPMAIF_UL_RESERVE_AO_RW */
#define DPMAIF_PCIE_MODE_SET_VALUE		(0x55)

/***********************************************************************
 *	DPMAIF interrupt
 **********************************************************************/
#define _UL_INT_DONE_OFFSET			0
#define _UL_INT_EMPTY_OFFSET			4
#define _UL_INT_MD_NOTRDY_OFFSET		8
#define _UL_INT_PWR_NOTRDY_OFFSET		12
#define _UL_INT_LEN_ERR_OFFSET			16

#define DPMAIF_DL_INT_DONE			BIT(0)
#define DPMAIF_DL_INT_SKB_LEN_ERR		BIT(1)
#define DPMAIF_DL_INT_BATCNT_LEN_ERR		BIT(2)
#define DPMAIF_DL_INT_PITCNT_LEN_ERR		BIT(3)
#define DPMAIF_DL_INT_PKT_EMPTY			BIT(4)
#define DPMAIF_DL_INT_FRG_EMPTY			BIT(5)
#define DPMAIF_DL_INT_LEN_ERR			BIT(6)

#define DPMAIF_UL_INT_ERR_MSK			(0x0F << _UL_INT_LEN_ERR_OFFSET)
#define DPMAIF_UL_INT_EMPTY_MSK			(0x0F << _UL_INT_EMPTY_OFFSET)
#define DPMAIF_UL_INT_MD_NOTREADY_MSK		(0x0F << _UL_INT_MD_NOTRDY_OFFSET)
#define DPMAIF_UL_INT_MD_PWR_NOTREADY_MSK	(0x0F << _UL_INT_PWR_NOTRDY_OFFSET)
#define DPMAIF_UL_INT_QDONE_MSK			(0x0F << _UL_INT_DONE_OFFSET)

#define DPMAIF_UDL_IP_BUSY			BIT(0)
#define DPMAIF_DL_INT_DLQ0_QDONE		BIT(8)
#define DPMAIF_DL_INT_DLQ1_QDONE		BIT(9)
#define DPMAIF_DL_INT_DLQ0_PITCNT_LEN		BIT(10)
#define DPMAIF_DL_INT_DLQ1_PITCNT_LEN		BIT(11)
#define DPMAIF_DL_INT_Q2TOQ1			BIT(24)
#define DPMAIF_DL_INT_Q2APTOP			BIT(25)
#define DPMAIF_DL_INT_Q2PCIETOP			BIT(30)

/***********************************************************************
 *	DPMAIF DLQ HW configure
 ***********************************************************************/
#define DPMAIF_HPC_DLQ_PATH_MODE		3
#define DPMAIF_HPC_ADD_MODE_DF			0
#define DPMAIF_HPC_TOTAL_NUM			8
#define DPMAIF_HPC_MAX_TOTAL_NUM		8
#define DPMAIF_AGG_MAX_LEN_DF			65535
#define DPMAIF_AGG_TBL_ENT_NUM_DF		50
#define DPMAIF_HASH_PRIME_DF			13
#define DPMAIF_MID_TIMEOUT_THRES_DF		100
#define DPMAIF_DLQ_TIMEOUT_THRES_DF		100
#define DPMAIF_DLQ_PRS_THRES_DF			10
#define DPMAIF_DLQ_HASH_BIT_CHOOSE_DF		0

#define DPMAIF_DLQPIT_EN_MSK			0x100000
#define DPMAIF_DLQPIT_CHAN_OFS			16
#define DPMAIF_ADD_DLQ_PIT_CHAN_OFS		20

enum pcie_int {
	DPMAIF_INT = 0,
	CLDMA0_INT,
	CLDMA1_INT,
	CLDMA2_INT,
	MHCCIF_INT,
	DPMAIF2_INT,
	SAP_RGU_INT,
	CLDMA3_INT,
	A_ATR_INT,
	P_ATR_INT,
};

union pcie_ltssm_status {
	struct {
		u32 LTSSM_DETECT              : 1;
		u32 LTSSM_POLLING             : 1;
		u32 LTSSM_CONFIGURATION       : 1;
		u32 LTSSM_RECOVERY            : 1;
		u32 LTSSM_L0                  : 1;
		u32 LTSSM_L0S                 : 1;
		u32 LTSSM_L1                  : 1;
		u32 LTSSM_L2                  : 1;
		u32 LTSSM_DISABLE             : 1;
		u32 LTSSM_LOOPBACK            : 1;
		u32 LTSSM_HOTRESET            : 1;
		u32 LINK_UNSTABLE             : 1;
		u32 L1PM_L11                  : 1;
		u32 L1PM_L12                  : 1;
		u32 LTSSM_RECOV_LOCK          : 1;
		u32 LTSSM_RECOV_EQUAL         : 1;
		u32 LTSSM_RECOV_SPEED         : 1;
		u32 LTSSM_RECOV_CFG           : 1;
		u32 RSVD1                     : 6;
		u32 LTSSM_state               : 5;
		u32 rsv_29                    : 3;
	} bits;
	u32 raw;
};

union istatus_local {
	struct {
		u32 rsv_16		      : 16;
		u32 A_ATR_EVT                 : 4;
		u32 P_ATR_EVT                 : 4;
		u32 INT_EVT                   : 4;
		u32 MSG_EVT                   : 1;
		u32 AER_L2_EVT                : 1;
		u32 PM_EVT                    : 1;
		u32 ERROR_RST_EVT             : 1;
	} bits;
	u32 raw;
};

union int_hst {
	struct {
		u32 rsv_16			: 16;
		u32 A_ATR_EVT			: 4;
		u32 P_ATR_EVT			: 4;
		u32 DPMAIF_INT			: 1;
		u32 CLDMA0_INT			: 1;
		u32 CLDMA1_INT			: 1;
		u32 CLDMA2_INT			: 1;
		u32 MHCCIF_INT			: 1;
		u32 DPMAIF2_INT			: 1;
		u32 SAP_RGU_INT			: 1;
		u32 CLDMA3_INT			: 1;
	} bits;
	u32 raw;
};

union istat_hst_ctrl {
	struct {
		u32 ISTAT_HST_DIS		: 1;
		u32 rsv_1			: 29;
		u32 RSVD			: 2;
	} bits;
	u32 raw;
};

union atr_pcie_win0_atr_param_src_addr_lsb {
	struct {
		u32 ATR_IMPL                  : 1;
		u32 ATR_SIZE                  : 6;
		u32 rsv_7                     : 5;
		u32 SRC_ADDR_LSB              : 20;
	} bits;
	u32 raw;
};

union atr_pcie_win0_trsl_addr_lsb {
	struct {
		u32 SRC_BAR                   : 4;
		u32 SRC_FUNC                  : 5;
		u32 rsv_9                     : 3;
		u32 TRSL_ADDR_LSB             : 20;
	} bits;
	u32 raw;
};

union atr_pcie_win0_trsl_param {
	struct {
		u32 TRSL_ID                   : 4;
		u32 rsv_4                     : 12;
		u32 TRSF_PARAM                : 12;
		u32 rsv_28                    : 4;
	} bits;
	u32 raw;
};

union pcie_low_pwr_ctrl {
	struct {
		u32 dis_lowpwr_mask           : 4;
		u32 rsv_4                     : 4;
		u32 force_dis_lowpwr          : 4;
		u32 rsv_12                    : 20;
	} bits;
	u32 raw;
};

#endif /* __T7XX_REG_H__ */
