ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_utils
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_cpas/include
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_sensor_module/cam_cci
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_sensor_module/cam_sensor_io
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_sensor_module/cam_sensor_utils
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_req_mgr
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_smmu/


obj-$(CONFIG_QTI_CCI) += cam_cci_dev.o cam_cci_core.o cam_cci_soc.o
