/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2019 - 2020 DisplayLink (UK) Ltd.
 */
#ifndef __MAUSB_MAUSB_DRIVER_STATUS_H__
#define __MAUSB_MAUSB_DRIVER_STATUS_H__

#define MAUSB_DRIVER_BAD_READ_BUFFER_SIZE  -1
#define MAUSB_DRIVER_RING_EVENTS_STOPPED   -2
#define MAUSB_DRIVER_SYSTEM_SUSPENDED      -3
#define MAUSB_DRIVER_COPY_TO_BUFFER_FAILED -4

#define MAUSB_DRIVER_READ_TIMEOUT 0
#define MAUSB_DRIVER_READ_ERROR  -1
#define MAUSB_DRIVER_WRITE_ERROR  -2

#endif /* __MAUSB_MAUSB_DRIVER_STATUS_H__ */
