ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_req_mgr
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_utils
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_sync
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_core
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_smmu
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_cdm
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_lrme
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_lrme/lrme_hw_mgr/
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_lrme/lrme_hw_mgr/lrme_hw
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_cpas/include/

obj-$(CONFIG_SPECTRA_CAMERA) += lrme_hw_mgr/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_lrme_dev.o cam_lrme_context.o
