ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_icp/icp_hw/include
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_icp/icp_hw/icp_hw_mgr/
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_icp/fw_inc/
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_smmu/
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_core
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_utils
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_sync
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_req_mgr/
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_icp/icp_hw/icp_hw_mgr/include/
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_icp/icp_hw/a5_hw/
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_cpas/include

obj-$(CONFIG_SPECTRA_CAMERA) += cam_icp_hw_mgr.o
