ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_utils
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_req_mgr
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_core
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_sync
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_smmu
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_cdm
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_fd
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_fd/fd_hw_mgr
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_fd/fd_hw_mgr/fd_hw
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_cpas/include

obj-$(CONFIG_SPECTRA_CAMERA) += cam_fd_hw_dev.o cam_fd_hw_core.o cam_fd_hw_soc.o
