# SPDX-License-Identifier: GPL-2.0+
# Renoir platform Support
snd-rn-pci-acp3x-objs	:= rn-pci-acp3x.o
snd-acp3x-rn-pdm-dma-objs	:= acp3x-rn-pdm-dma.o
snd-acp3x-rn-pcm-dma-objs  := acp3x-rn-pcm-dma.o
snd-acp3x-rn-i2s-objs      := acp3x-rn-i2s.o
snd-soc-acp-rn-rt5682-mach-objs := rn-rt5682-rt1019.o

obj-$(CONFIG_SND_SOC_AMD_RENOIR)	+= snd-rn-pci-acp3x.o
obj-$(CONFIG_SND_SOC_AMD_RENOIR)	+= snd-acp3x-rn-pdm-dma.o
obj-$(CONFIG_SND_SOC_AMD_RENOIR)	+= snd-acp3x-rn-pcm-dma.o
obj-$(CONFIG_SND_SOC_AMD_RENOIR)	+= snd-acp3x-rn-i2s.o
obj-$(CONFIG_SND_SOC_AMD_RENOIR_MACH)   += snd-soc-acp-rn-rt5682-mach.o
