ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_utils
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_cpas/include
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_sensor_module/cam_sensor_io
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_sensor_module/cam_sensor_utils
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_sensor_module/cam_cci
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_req_mgr
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_smmu/
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_core

obj-$(CONFIG_QTI_SENSORS) += cam_csiphy_soc.o cam_csiphy_dev.o cam_csiphy_core.o
