ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_utils
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_sync
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_sensor_module/cam_res_mgr
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_sensor_module/cam_sensor_utils
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_sensor_module/cam_sensor_io
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_sensor_module/cam_cci
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_req_mgr
ccflags-y += -I$(srctree)/drivers/media/platform/camx/cam_smmu/

obj-$(CONFIG_QTI_IR_LED) += cam_ir_led_dev.o cam_ir_led_soc.o cam_ir_led_core.o
